server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://config.platform:9000
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/books/**
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/members/**
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/files/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
